name: Build, Test, Deployment
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Hello world
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
        id: hello

      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'

      - name: Sample secret key
        with:
          super_secret: ${{ secrets.SAMPLE_SECRET_KEY }}
        run: |
          echo "Super secret should be redacted $super_secret"