name: Build, Test, Deployment
on: [push]

jobs:
  build:
    name: Fiddling with build actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Build with Maven
        run: mvn clean package

      - name: Specific python version and secret keys
        uses: actions/setup-python@v1
        env:
          env_secret: ${{ secrets.SAMPLE_SECRET_KEY }}
        with:
          python-version: '3.8'
          architecture: 'x64'
          secret: ${{ secrets.SAMPLE_SECRET_KEY }}

      - name: Can you share a secret?
        run: echo "Super secret should be redacted $secret"

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests
          python build-with-actions.py $secret $env_secret